--
-- Table structure for table `sensors`
--

CREATE TABLE `sensors` (
  `ID` mediumint(8) unsigned NOT NULL auto_increment COMMENT 'Row index',
  `TimeOfRec` datetime NOT NULL COMMENT 'Date and time at the end of measurement period [UTC]',
  `RecNbr` bigint(20) unsigned default NULL COMMENT 'Data logger record number',
  `T(1)` float default NULL COMMENT 'Average outdoor temperature [deg C] (sensor #1)',
  `T(2)` float default NULL COMMENT 'Average outdoor temperature [deg C] (sensor #2)',
  `T_Min(1)` float default NULL COMMENT 'Minimum outdoor temperature [deg C] (sensor #1)',
  `T_Min(2)` float default NULL COMMENT 'Minimum outdoor temperature [deg C] (sensor #2)',
  `T_Max(1)` float default NULL COMMENT 'Maximum outdoor temperature [deg C] (sensor #1)',
  `T_Max(2)` float default NULL COMMENT 'Maximum outdoor temperature [deg C] (sensor #2)',
  `RH(1)` float default NULL COMMENT 'Average outdoor relative humidity [% rH] (sensor #1)',
  `RH(2)` float default NULL COMMENT 'Average outdoor relative humidity [% rH] (sensor #2)',
  `RH_Min(1)` float default NULL COMMENT 'Minimum outdoor relative humidity [% rH] (sensor #1)',
  `RH_Min(2)` float default NULL COMMENT 'Minimum outdoor relative humidity [% rH] (sensor #2)',
  `RH_Max(1)` float default NULL COMMENT 'Maximum outdoor relative humidity [% rH] (sensor #1)',
  `RH_Max(2)` float default NULL COMMENT 'Maximum outdoor relative humidity [% rH] (sensor #2)',
  `VWind(1)` float default NULL COMMENT 'Average wind speed [m/s] (sensor #1)',
  `VWind(2)` float default NULL COMMENT 'Average wind speed [m/s] (sensor #2)',
  `VWind_Min(1)` float default NULL COMMENT 'Minimum wind speed [m/s] (sensor #1)',
  `VWind_Min(2)` float default NULL COMMENT 'Minimum wind speed [m/s] (sensor #2)',
  `VWind_Max(1)` float default NULL COMMENT 'Maximum wind speed [m/s] (sensor #1)',
  `VWind_Max(2)` float default NULL COMMENT 'Maximum wind speed [m/s] (sensor #2)',
  `P(1)` float default NULL COMMENT 'Average outdoor pressure [hPa] (sensor #1)',
  `P(2)` float default NULL COMMENT 'Average outdoor pressure [hPa] (sensor #2)',
  `P_Min(1)` float default NULL COMMENT 'Minimum outdoor pressure [hPa] (sensor #1)',
  `P_Min(2)` float default NULL COMMENT 'Minimum outdoor pressure [hPa] (sensor #2)',
  `P_Max(1)` float default NULL COMMENT 'Maximum outdoor pressure [hPa] (sensor #1)',
  `P_Max(2)` float default NULL COMMENT 'Maximum outdoor pressure [hPa] (sensor #2)',
  `GRad` float default NULL COMMENT 'Average global radiation [W/m^2]',
  `GRad_Min` float default NULL COMMENT 'Minimum global radiation [W/m^2]',
  `GRad_Max` float default NULL COMMENT 'Maximum global radiation [W/m^2]',
  `T_FTIR(1)` float default NULL COMMENT 'Average temperature inside FTIR [deg C] (sensor #1)',
  `T_FTIR(2)` float default NULL COMMENT 'Average temperature inside FTIR [deg C] (sensor #2)',
  `T_indoor` float default NULL COMMENT 'Average temperature inside container [deg C]',
  `RH_indoor` float default NULL COMMENT 'Average relative humidity inside container [% rH]',
  `T_dome` float default NULL COMMENT 'Average temperature inside solar tracker dome [deg C]',
  `RH_dome` float default NULL COMMENT 'Average relative humidity inside solar tracker dome [% rH]',
  `N` tinyint(3) unsigned default NULL COMMENT 'Number of samples in measurement period',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `TimeOfRec` (`TimeOfRec`)
) ENGINE=MyISAM AUTO_INCREMENT=558462 DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci CHECKSUM=1 COMMENT='Indoor and outdoor sensors from data logger';
